### ISSUE TITLE
[pgadmin] template: pgadmin4/templates/ingress.yaml:35:21: executing "pgadmin4/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}

### ISSUE THREAD

**Issue by viceice** [rowanruseler/helm-charts#100]
**Describe the bug**
A new error occures on 1.5.9

``` 
template: pgadmin4/templates/ingress.yaml:35:21: executing "pgadmin4/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}
```

**Version of Helm and Kubernetes**:
Kubernetes: v1.20.5+k3s1
Helm: 2.0.3 ( using Terraform)

**Which chart**:
pgadmin4 1.5.9 (upgrade from 1.5.6)

**What happened**:
Upgrade fails with error above

**What you expected to happen**:
Should  update

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

I think it's again related to #90

**Comment by rowanruseler** [comment]
@viceice no this is correct, I informed you that the paths have been adjusted. Look at the example in values.yaml to see how they should be defined now.

**Comment by viceice** [comment]
Sorry, forgot about the path change in patch release 😕 

```yaml
image:
  repository: dpage/pgadmin4
  tag: '5.1'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: pga.xxxxx.yy
      paths:
        - /
```
