### ISSUE TITLE
bug in ingress.yaml:  path: {{ .path }} should be  path: {{ . }}

### ISSUE THREAD

**Issue by johannges** [rowanruseler/helm-charts#101]
**Describe the bug**
There is a bug in ingress.yaml. The problem is in line 35:

is:
`- path: {{ .path }}`

Should be:

`- path: {{ . }}`

**Comment by rowanruseler** [comment]
@johannges this is not a bug, I implemented this a few pull requests back. Apologies, you will need to make an adjustment in your values file.

pre adjustment:
```
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
```

post adjustment:
```

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
```
