### ISSUE TITLE
[runix/pgadmin4] Pgadmin4 non root user kubernetes Failed to create the directory /var/log/pgadmin:

### ISSUE THREAD

**Issue by an-sy** [rowanruseler/helm-charts#103]
**Describe the bug**
I want to deploy pgadmin in a Openshift environment, where it is not allowed to give pods root access:
I deploy the chart with th following config

securityContext:
  runAsUser: Null
  runAsGroup: Null
  fsGroup: Null

the chart deployment works perfectly, also the pod runs with following error:
non root user kubernetes Failed to create the directory /var/log/pgadmin: [Errno 13] Permission denied: '/var/log/pgadmin'

**Version of Helm and Kubernetes**:

helm_version v3.4.2

Kubernetes v1.19.0+9c69bdc (Openshift 4)

**Which chart**:
runix/pgadmin4
**What happened**:
non root user kubernetes Failed to create the directory /var/log/pgadmin: [Errno 13] Permission denied: '/var/log/pgadmin'

**What you expected to happen**:

should create mountpoint

**How to reproduce it** (as minimally and precisely as possible):
set Securtycontext:
securityContext:
  runAsUser: Null
  runAsGroup: Null
  fsGroup: Null

**Anything else we need to know**:

**Comment by NangiDev** [comment]
I think you could get around this by setting VolumePermissions.

I used a Values.yaml file that looks like this
``` yaml
persistentVolume:
        enabled: true
        existingClaim: <your claim name>

VolumePermissions:
  # chown -R pgadmin:pgadmin /var/lib/pgadmin
  enabled: true
```

Then just ran the command `helm install <name> runix/pgadmin4 -f Values.yaml`
