### ISSUE TITLE
need 9.4.24 postgres binary included 

### ISSUE THREAD

**Issue by ronaldjeden** [rowanruseler/helm-charts#114]
Hi Guys,

I am trying to deploy this chart, I would also need the 9.4.24 postgres binary to be available for connecting to our greenplum instances.

Is this easy to do? Can someone give me some pointers?

Would be grateful if you guys could help me out. Thanx for all your work so far.

**Comment by rowanruseler** [comment]
@ronaldjeden you are able to build your own image and add the postgres binary, and in the values file adjust these settings to your own image:

```
image:
  registry: docker.io
  repository: dpage/pgadmin4
  tag: "5.7"                                                                                                                                                   
  pullPolicy: IfNotPresent
```
