### ISSUE TITLE
[runix/pgadmin4] Internal server error 

### ISSUE THREAD

**Issue by Iamafirestarter** [rowanruseler/helm-charts#134]
The issue is that after enabling ouath2, Pgadmin crashes with the 500 error and the following in the logs:

  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put
    dump(
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed

**Comment by rowanruseler** [comment]
Apologies for the late reply, can you provide me an overview of your values file?

**Comment by guyguy333** [comment]
@rowanruseler Having similar issue. Here are files:

values.yaml:

```
serviceAccount:
  create: true

serverDefinitions:
  enabled: true
  servers:
    # xxxx

networkPolicy:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: pgadmin.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - pgadmin.example.com

extraSecretMounts:
  - name: config-local
    secret: pgadmin4-config-local
    subPath: config_local.py
    mountPath: "/pgadmin4/config_local.py"
    readOnly: true

persistentVolume:
  enabled: true
  size: 1Gi
```

config-local secret: 

```
kind: Secret
apiVersion: v1
metadata:
  name: pgadmin4-config-local
type: Opaque
stringData:
  config_local.py: |-
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['oauth2']
    OAUTH2_AUTO_CREATE_USER = True
    OAUTH2_CONFIG = [
      {
          'OAUTH2_NAME': 'authentik',
          'OAUTH2_DISPLAY_NAME': 'Authentik',
          'OAUTH2_CLIENT_ID': 'xxxxxx',
          'OAUTH2_CLIENT_SECRET': 'xxxxx',
          'OAUTH2_TOKEN_URL': 'https://sso.example.com/application/o/token/',
          'OAUTH2_AUTHORIZATION_URL': 'https://sso.example.com/application/o/authorize/',
          'OAUTH2_API_BASE_URL': 'https://sso.example.com/',
          'OAUTH2_USERINFO_ENDPOINT': 'https://sso.example.com/application/o/userinfo/',
          'OAUTH2_SCOPE': 'openid email profile'
      }
    ]
```

Chart version: `1.9.6`
