### ISSUE TITLE
[pgadmin4] allow custom volumes & volumeMounts

### ISSUE THREAD

**Issue by schnapsidee** [rowanruseler/helm-charts#140]
I'm currently in the process of moving all existing secrets to Hashicorp Vault and use the [Vault CSI Provider](https://www.vaultproject.io/docs/platform/k8s/csi) to mount secrets as env vars. To do that I need to create a custom volume and mount. Unfortunately the existing templates only allows very limited mounts of configMap and secrets. 

The CSI Provider needs to create a volume in a specific format, which isn't compatible with the way the current deployment template is set up: 
``` yaml
volumes:
    - name: vault-db-creds
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: 'vault-db-creds'
```

**Possible solutions**

Add an option for extraVolumes in the values.yaml and the following block to the deployment template: 
``` yaml
volumes:
    {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
    {{- end }}
```
The same would be necessary for extraVolumeMounts since the current secretMount implementation doesn't allow for custom mountPaths.

I'd be willing to create a PR, if you're interested.
If you consider this out of scope, that's fine. I'd just like a response so I can decide if I want to fork or not. Thanks :)
