### ISSUE TITLE
pgadmin4: Ingress with enabled TLS

### ISSUE THREAD

**Issue by frankvollenweider** [rowanruseler/helm-charts#20]
Hi @rowanruseler ,

I am trying to install pgadmin4 into a GKE cluster using Jenkins-x. Unfortunately the promotion build is already unsuccessful. The following command results in an error:

helm lint --set tags.jx-lint=true --set global.jxLint=true --set-string global.jxTypeEnv=lint --values values.yaml

Console log:

Successfully added Helm repository helm.runix.net.
error: failed to lint the chart '.': failed to run 'helm lint --set tags.jx-lint=true --set global.jxLint=true --set-string global.jxTypeEnv=lint --values values.yaml' command in directory '.', output: '2020/05/06 15:16:16 Warning: Merging destination map for chart 'pgadmin4'. The destination item 'tls' is a table and ignoring the source 'tls' as it has a non-table value of: []
2020/05/06 15:16:16 Warning: Merging destination map for chart 'pgadmin4'. The destination item 'tls' is a table and ignoring the source 'tls' as it has a non-table value of: []
2020/05/06 15:16:16 Warning: Merging destination map for chart 'pgadmin4'. The destination item 'tls' is a table and ignoring the source 'tls' as it has a non-table value of: []
2020/05/06 15:16:16 Warning: Merging destination map for chart 'pgadmin4'. The destination item 'tls' is a table and ignoring the source 'tls' as it has a non-table value of: []
==> Linting .
[ERROR] templates/: render error in "env/charts/pgadmin4/templates/ingress.yaml": template: env/charts/pgadmin4/templates/ingress.yaml:18:16: executing "env/charts/pgadmin4/templates/ingress.yaml" at <.hosts>: can't evaluate field hosts in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed'
make: *** [build] Error 1

Pipeline failed on stage 'pr-checks' : container 'step-lint-env-helm'. The execution of the pipeline has stopped.

I attached my values.yaml file (added .txt at the end of the filename to be able to attach it):
[values.yaml.txt](https://github.com/rowanruseler/helm-charts/files/4587794/values.yaml.txt)

Can you please show me what I'm doing wrong?

pgadmin4 chart version: 1.2.14

Environment:
jx                 2.1.13+cjxd.9
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS

Many thanks in advance!

**Comment by rowanruseler** [comment]
Hi @frankvollenweider, could you show me your ingress configuration from within the values.yaml?

e.g.:
```
ingress:
  enabled: false

  annotations: {}

  hosts:
    - host: chart-example.local
      paths: []

  tls: []
```

**Comment by rowanruseler** [comment]
hi @frankvollenweider,

Looks like you made an indentation mistake within your tls part, please see the correct example below:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: pgadmin4-jx.dev.mydomain.swiss
      paths: []
  tls:
    - secretName: tls-dev-my-domain-swiss-p
      hosts:
        - pgadmin4-jx.dev.mydomain.swiss
```
