### ISSUE TITLE
[pgadmin4] volume override not working after 1.18.3

### ISSUE THREAD

**Issue by 616slayer616** [rowanruseler/helm-charts#231]
Starting with 1.18.3 I can neither upgrade from 1.18.2 nor uninstall and then install the chart.

This PR https://github.com/rowanruseler/helm-charts/pull/226 made changes that prevent me from upgrading.

I'm getting this error:
```
Error: 1 error occurred:
	* Deployment.apps "pgadmin-pgadmin4" is invalid: [spec.template.spec.volumes[1].configMap.name: Required value, spec.template.spec.containers[0].volumeMounts[2].name: Not found: "pgadmin4-config"]
```

**How to reproduce it** (as minimally and precisely as possible):

values:
```
extraConfigmapMounts:
  - name: config-local
    configMap: pgadmin4-config
    subPath: config_local.py
    mountPath: "/pgadmin4/config_local.py"
    readOnly: true
```

config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-config
data:
  config_local.py: |-
    import os

    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['oauth2', 'internal']
    OAUTH2_AUTO_CREATE_USER = True
    OAUTH2_CONFIG = [
      {
          'OAUTH2_NAME': 'google',
          'OAUTH2_DISPLAY_NAME': 'Google',
          'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
          'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
          'OAUTH2_TOKEN_URL': 'https://www.googleapis.com/oauth2/v3/token',
          'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/v2/auth',
          'OAUTH2_API_BASE_URL': 'https://www.googleapis.com/oauth2/v3/',
          'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
          'OAUTH2_ICON': 'fa-google',
          'OAUTH2_BUTTON_COLOR': '#0000ff',
      }
    ]
```
