### ISSUE TITLE
[pgadmin4] Unable to use extraInitContainers on versions above 1.2.14

### ISSUE THREAD

**Issue by alextennantovo** [rowanruseler/helm-charts#24]
**Describe the bug**
When using versions of the chart above 1.2.14 `initContainers` is rendered with an extra `- name` when `extraInitContainers` is specified.

**Version of Helm and Kubernetes**:
Helm 3.2.0

**Which chart**:
pgadmin4

**What happened**:
Rendered:
```
    spec:
      initContainers:
        
        - name: chmod-pgpassfile
          image: dpage/pgadmin4:4.21
          imagePullPolicy: IfNotPresent
          command: ["/bin/chmod", "0600", "/etc/pgadmin4/pgpassfile"]
          volumeMounts:
            - name: pgpassfile
              mountPath: /etc/pgadmin4
          securityContext:
            runAsUser: 0
        
        - name
```

**What you expected to happen**:
```
    spec:
      initContainers:
        - name: chmod-pgpassfile
          image: dpage/pgadmin4:4.21
          imagePullPolicy: IfNotPresent
          command: ["/bin/chmod", "0600", "/etc/pgadmin4/pgpassfile"]
          volumeMounts:
            - name: pgpassfile
              mountPath: /etc/pgadmin4
          securityContext:
            runAsUser: 0
```

**How to reproduce it** (as minimally and precisely as possible):
`helm template pgadmin runix/pgadmin4 -f pgadmin-values.yaml` using the following values:

```
extraInitContainers: |
  - name: chmod-pgpassfile
    image: dpage/pgadmin4:4.21
    imagePullPolicy: IfNotPresent
    command: ["/bin/chmod", "0600", "/etc/pgadmin4/pgpassfile"]
    volumeMounts:
      - name: pgpassfile
        mountPath: /etc/pgadmin4
    securityContext:
      runAsUser: 0
```

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Hi @alextennantovo,

Within the default values.yaml file I adjusted the following:
```
VolumePermissions:
  ## If true, enables an InitContainer to set permissions on /var/lib/pgadmin.
  ##
  enabled: true
```

Then I ran your specific command, but adjusted pgadmin-values.yaml to just values.yaml, and these are my results:
```

    spec:
      initContainers:
        - name: init-pgadmin
          image: "dpage/pgadmin4:4.21"
          imagePullPolicy: IfNotPresent
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
          securityContext:
            runAsUser: 0
```

version of helm:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Conclusion: I'm unable to reproduce. Please share your whole values file with me.
