### ISSUE TITLE
[pgadmin4] config_local.py not loading?

### ISSUE THREAD

**Issue by dorkest-dork** [rowanruseler/helm-charts#278]
**Describe the bug**
I'd expect the config_local.py injected through a ConfigMap using extraVolumeMounts and extraVolumes should be loaded during startup but seems it doesn't. Volume mount works and file is present in /pgadmin4/config_local.py.

**Version of Helm and Kubernetes**:
helm v3.16.2
Google GKE

**Which chart**:
runix/pgadmin4 1.37.0

**What happened**:
config_local.py has no effect.

**What you expected to happen**:
config_local.py gets processed.

**How to reproduce it** (as minimally and precisely as possible):
- kubectl create configmap pgadmin4-config-local --from-file=config_local.py=./config_local.py -n pgadmin4
- set in values.yaml:
```
extraVolumes:
  - name: config-local
    configMap:
      name: pgadmin4-config-local

extraVolumeMounts:
  - name: config-local
    mountPath: /pgadmin4/config_local.py
    subPath: config_local.py
    readOnly: true
```
- deploy with helm

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Thank you for reporting an issue, can we get more verbose logs to see on what it is failing specifically?

```
envVarsExtra:
  - name: PGADMIN_CONFIG_DEBUG
    value: True
  - name: CONSOLE_LOG_LEVEL
    value: logging.DEBUG
  - name: FILE_LOG_LEVEL
    value: logging.DEBUG
```
