### ISSUE TITLE
[pgadmin4] hostAliases - hostnames section missing from deployment

### ISSUE THREAD

**Issue by amir-yousef** [rowanruseler/helm-charts#279]
**Describe the bug**
When settings hostAliases in the values, the rendered deployment manifest is missing the "hostnames" section.
Only the "ip" section is present.

Values:

```
  pgadmin4:
    hostAliases:
      - ip: "10.0.0.2"
        hostnames:
        - "pgadmin1.local"
```

Output in deployment:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
  template:
...
    spec:
...
      hostAliases:
      - ip: 10.0.0.2
      initContainers:
```

I believe its because in the template below "hostname" needs to be "hostnames":
https://github.com/rowanruseler/helm-charts/blob/c422b73887edcd16d401a6ecd7cdb092af6766e0/charts/pgadmin4/templates/deployment.yaml#L53

**Version of Helm and Kubernetes**:

Helm - v3.15.1
Kubernetes - v1.31.2

**Which chart**:

pgadmin4/1.37.0

**What happened**:

"hostnames" section missing under "hostAliases" in the rendered deployment manifest.

**What you expected to happen**:

"hostnames" section to be present under "hostAliases"

**How to reproduce it** (as minimally and precisely as possible):

Add hostAliases section to the values file.
Install the pgadmin4 chart.

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Thank you for pointing this out, please see #282, running a test now results in:

```
---
# Source: pgadmin4/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pgadmin4.local"
```
