### ISSUE TITLE
ServiceAccount Annotations aren't working

### ISSUE THREAD

**Issue by ajventer** [rowanruseler/helm-charts#313]
The sample values file, and the README.md both list annotations as a supported field in ServiceAccount.
However, when set in the values files, this field is not set in the deployed resources, using helm template, it is not present in the deployed output.

Example:
-  values file snippet:
```
serviceAccount:
  create: true
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::#####:role/employee_mutations_db_app_user
  name: "#####-serviceaccount"
  automountServiceAccountToken: true
```

(I used python to validate that the yaml is correct, and the subways are in the right places).
>>> y['serviceAccount']['annotations']['eks.amazonaws.com/role-arn']
'arn:aws:iam::######:role/employee_mutations_db_app_us

However in a rendered helm template output:

    spec:
      serviceAccountName: employee-mutations-serviceaccount
      automountServiceAccountToken: true
      containers:

The Annotations are missing.

**Version of Helm and Kubernetes**:
helm 3.18.3
kubernetes 1.32 (since helm template reproduces the error locally I don't think the k8s version is relevant to the bug but here it is anyway)

**Which chart**:
pgadmin4

**What happened**:
The annotation is not rendered

**What you expected to happen**:
For the annotation to be rendered, and ultimately deployed

**How to reproduce it** (as minimally and precisely as possible):
I believe the data in the bug description should allow for easy reproduction - helm chart should repeat the error

**Anything else we need to know**:
I don't think so, but I'll answer any questions you have
