### ISSUE TITLE
Failing to start Chart on AKS - no errors

### ISSUE THREAD

**Issue by anthonysomerset** [rowanruseler/helm-charts#45]
Hi There

i am trying to deploy this chart on Azure Kubernetes service (running kubernetes v1.17.9), here are my values.yaml

```
env:
  email: admin@domain
  password: <REDACTED>
  variables:
    - name: PGADMIN_LISTEN_ADDRESS
      value: "0.0.0.0"
persistentVolume:
  storageClass: azurefilepgadmin
service:
  type: LoadBalancer
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: "pgadmin.azure.domain."
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
VolumePermissions:
      ## If true, enables an InitContainer to set permissions on /var/lib/pgadmin.
      ## 
  enabled: true
```

i get no real errors in the logs other than what appear to be just warnings:

```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
[2020-09-11 06:51:17 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-09-11 06:51:17 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-09-11 06:51:17 +0000] [1] [INFO] Using worker: threads
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-09-11 06:51:17 +0000] [88] [INFO] Booting worker with pid: 88
```

however the container never seems to become "available" if i open a shell up in the container i can see the gunicorn process has started and listening on port 80 but it just does not respond and no error gets emitted in logs. In the kubernetes events this is also correlated by the liveness and readiness probles also failing

```
  Warning  Unhealthy         45s        kubelet, aks-prdakspool1-37452914-vmss000001  Liveness probe failed: Get http://10.181.67.42:80/misc/ping: dial tcp 10.181.67.42:80: connect: connection refused
  Warning  Unhealthy         40s        kubelet, aks-prdakspool1-37452914-vmss000001  Readiness probe failed: Get http://10.181.67.42:80/misc/ping: dial tcp 10.181.67.42:80: connect: connection refused
```

am currently at a loss as to how to debug further or next steps towards a resolution
