### ISSUE TITLE
[pgadmin4] expose config_local.py in values.yml

### ISSUE THREAD

**Issue by mfbrj** [rowanruseler/helm-charts#47]
**Is your feature request related to a problem? Please describe.**
pgAdmin4 supports [ldap authentication](https://www.pgadmin.org/docs/pgadmin4/4.26/enabling_ldap_authentication.html). The config is enabled if we put some parameters in `config_local.py`, which can be inject in the pod by configmap, such as:
`key: config_local.py`
value:
```
import os
AUTHENTICATION_SOURCES = ['ldap', 'internal']
LDAP_AUTO_CREATE_USER = False
LDAP_CONNECTION_TIMEOUT = 30
LDAP_SERVER_URI = 'ldap://myldap.domain.com:389'
LDAP_SEARCH_BASE_DN = 'dc=mydomain,dc=com'
LDAP_USERNAME_ATTRIBUTE = 'sAMAccountName'
LDAP_BIND_USER = os.environ['LDAP_BIND_USER']
LDAP_BIND_PASSWORD = os.environ['LDAP_BIND_PASSWORD']
```
This configmap can be mounted as a volume in `/pgadmin4/config_local.py`. This is enough to pgadmin ldap authentication works with the current image `4.26`.

**Describe the solution you'd like**
It would be worth if we could put only the content of the `config_local.py` in `values.yml` and the chart does all the rest (creates the configmap and mount the volume in `/pgadmin4/config_local.py`), such as:

```
config_local: |
  # put here the values you want to be mounted in /pgadmin4/config_local.py
  # such as to enable ldap autenthication: 
  # import os
  # AUTHENTICATION_SOURCES = ['ldap', 'internal']
  # LDAP_AUTO_CREATE_USER = False
  # LDAP_CONNECTION_TIMEOUT = 30
  # LDAP_SERVER_URI = 'ldap://myldap.domain.com:389'
  # LDAP_SEARCH_BASE_DN = 'dc=domain,dc=com'
  # LDAP_USERNAME_ATTRIBUTE = 'sAMAccountName'
  # LDAP_BIND_USER = os.environ['LDAP_BIND_USER']
  # LDAP_BIND_PASSWORD = os.environ['LDAP_BIND_PASSWORD']
```

**Describe alternatives you've considered**
In addition, the values.yml could accept a existing secret with the keys `user` and `password`, to bind in the ldap, and the chart automatically put the values as enviroment variables LDAP_BIND_USER and LDAP_BIND_PASSWORD in the pod, such as:
```
ldap_bind_secret: ldap-bind
  # an existing secret with keys user and password to be
  # exposted as enviroment variables LDAP_BIND_USER and LDAP_BIND_PASSWORD 
  # in the pod.
```

**Additional context**

**Comment by rowanruseler** [comment]
Hi @mfbrj,

Since this is a container deployment, please read the following documentation is advised: https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html

Here you can find the following:

> PGADMIN_CONFIG_
> 
> This is a variable prefix that can be used to override any of the configuration options in pgAdmin’s config.py file. Add the PGADMIN_CONFIG_ prefix to any variable name from config.py and give the value in the format ‘string value’ for strings, True/False for booleans or 123 for numbers. See below for an example.
> 
> Settings are written to /pgadmin4/config_distro.py within the container, which is read after /pgadmin4/config.py and before /pgadmin4/config_local.py. Any settings given will therefore override anything in config.py, but can be overridden by settings in config_local.py.
> 
> See The [config.py File](https://www.pgadmin.org/docs/pgadmin4/development/config_py.html#config-py) for more information on the available configuration settings.


So in your case, as a small example:

```
  ## Add custom environment variables that will be injected to deployment
  ## Ref: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  ##
  variables:
    - name: PGADMIN_CONFIG_LDAP_SERVER_URI
      value: "ldap://myldap.domain.com:389"
    - name: PGADMIN_CONFIG_LDAP_BIND_USER
      value: "user"
    - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
      value: "supersecret"
```

Let me know if this is the solution you where looking for.

**Comment by mfbrj** [comment]
Hi, @rowanruseler 
Thanks for your help. It works with the following content in `values.yml`:
```
env:
  variables:
    - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
      value: "['ldap', 'internal']"
    - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
      value: "False"
    - name: PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT
      value: 30
    - name: PGADMIN_CONFIG_LDAP_SERVER_URI
      value: "'ldap://srvsededc01.redetre.jus.br:389'"
    - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
      value: "'dc=redetre,dc=jus,dc=br'"
    - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
      value: "'sAMAccountName'"
    - name: PGADMIN_CONFIG_LDAP_BIND_USER
      value: "'rancher'"
    - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
      value: "'mypassword'"
```
Which generates the following `config_distro.py`:
```
HELP_PATH = '../../docs'
DEFAULT_BINARY_PATHS = {
        'pg': '/usr/local/pgsql-12'
}
LDAP_SEARCH_BASE_DN = 'dc=redetre,dc=jus,dc=br'
LDAP_AUTO_CREATE_USER = False
LDAP_SERVER_URI = 'ldap://srvsededc01.redetre.jus.br:389'
AUTHENTICATION_SOURCES = ['ldap', 'internal']
ENHANCED_COOKIE_PROTECTION = False
LDAP_USERNAME_ATTRIBUTE = 'sAMAccountName'
LDAP_BIND_PASSWORD = 'mypassword'
LDAP_CONNECTION_TIMEOUT = 30
LDAP_BIND_USER = 'rancher'
```
I needed to use `"` and `'` to avoid errors when the values are transposed in to `config_distro.py`.

Unfortunally, the `LDAP_BIND_PASSWORD` is exposed in `values.yml`.

Any hint about how to use a secret on that?

**Comment by rowanruseler** [comment]
You could add perhaps an enabled state and add that into the templates::secrets.yaml for a case like this. Or if you already use something like vault, use that.

**Comment by mfbrj** [comment]
What you mean about 

> enabled state and add that into the templates::secrets.yaml

?

**Comment by mfbrj** [comment]
@rowanruseler 
This ugly construction works in python:
`DUMMY_VARIABLE = exec('import os\nLDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD")')`

So it's possible to use in values.yml:
```
variables:
    - name: PGADMIN_CONFIG_DUMMY_VARIABLE
      value: "exec('import os\nLDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD")')"
```

To complete the configuration, it would be nice if the `existingSecret` in values.yml has these additional parameters:
```
## Provide the name for an existing secret.
## Useful to avoid specifying password and server config in YAML files
existingSecret: "my-secret"
  - exposed_as_environment_variable: true
  - variable_name: "MY_VARIABLE"
```

**Comment by rowanruseler** [comment]
You can add those settings to existingSecret within your own values file. Just create a secret and then use in within this chart.

**Comment by mfbrj** [comment]
> To complete the configuration, it would be nice if the `existingSecret` in values.yml has these additional parameters:
> 
> ```
> ## Provide the name for an existing secret.
> ## Useful to avoid specifying password and server config in YAML files
> existingSecret: "my-secret"
>   - exposed_as_environment_variable: true
>   - variable_name: "MY_VARIABLE"
> ```

@rowanruseler can you implement this in the char?

**Comment by rowanruseler** [comment]
existingSecret uses a secret that already exists. Why should I add this towards the chart:
```
  - exposed_as_environment_variable: true
  - variable_name: "MY_VARIABLE"
```

This should be added in your own local variables.

**Comment by mfbrj** [comment]
Because these new parameters would tell the chart to expose the existingSecret as an enviroment variable. So we can use that env variable in the the config_distro.py with out any password in plain text in values.yml.

**Comment by mfbrj** [comment]
@rowanruseler it works with there values:

```
existingSecret: mysecret
env:
  email: mylogin@mydomain.com
  variables:
    - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
      value: "['ldap', 'internal']"
    - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
      value: "False"
    - name: PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT
      value: 30
    - name: PGADMIN_CONFIG_LDAP_SERVER_URI
      value: "'ldap://myldap.mydomain.com:389'"
    - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
      value: "'dc=mydomain,dc=com'"
    - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
      value: "'sAMAccountName'"
    - name: PGADMIN_CONFIG_LDAP_BIND_USER
      value: "'myldapuser'"
    - name: PGADMIN_CONFIG_DUMMY_VARIABLE
      value: "exec(\"import os\\nLDAP_BIND_PASSWORD = os.getenv('PGADMIN_DEFAULT_PASSWORD')\")"
```
