### ISSUE TITLE
[pgadmin4] Cannot redirect to pgadmin4 when using proxy

### ISSUE THREAD

**Issue by waseem-h** [rowanruseler/helm-charts#55]
Hi,
I'm facing issues when trying to use keycloak gatekeeper in front of pgadmin4. This is my helm values:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: hal-dev
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: pgadmin4
  helmVersion: v3
  chart:
    repository: https://helm.runix.net
    name: pgadmin4
    version: 1.3.6
  values:
    serverDefinitions:
      enabled: true
    VolumePermissions:
      enabled: true
    env:
      email: admin@domain.com
      pgpassfile: /var/lib/pgadmin/storage/pgadmin/file.pgpass
    image:
      repository: dpage/pgadmin4
      tag: 4.27
    existingSecret: pgadmin4
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-redirect-from: "~^http://([^/]+)/(.*)$"
        nginx.ingress.kubernetes.io/proxy-redirect-to: "https://pgadmin4-hal-dev.domain.com/$2"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
      - host: pgadmin4-hal-dev.domain.com
        paths:
        - /
      tls:
      - hosts:
        - pgadmin4-hal-dev.k8s.domain.com
        secretName: pgadmin4-tls
    persistentVolume:
      enabled: true
      storageClass: nfs
      size: 1Gi
    extraSecretMounts:
    - name: pgpassfile
      secret: pgadmin4
      subPath: file.pgpass
      mountPath: "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
      defaultMode: 0600
    extraConfigmapMounts:
    - name: gatekeeper-config
      configMap: pgadmin4-gatekeeper-config
      readOnly: true
      mountPath: /etc/keycloak-gatekeeper.conf
      subPath: keycloak-gatekeeper.conf
    extraInitContainers: |
      - name: add-folder-for-pgpass
        image: "dpage/pgadmin4:4.27"
        command: ["/bin/mkdir", "-p", "/var/lib/pgadmin/storage/pgadmin"]
        volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
        securityContext:
          runAsUser: 5050
    extraContainers: |
      - name: proxy
        image: quay.io/louketo/louketo-proxy:1.0.0
        args:
        - --config=/etc/keycloak-gatekeeper.conf
        ports:
        - name: proxy-web
          containerPort: 3000
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/keycloak-gatekeeper.conf
          subPath: keycloak-gatekeeper.conf
    service:
      targetPort: proxy-web
```

And my gatekeeper config:
```
    discovery-url: https://keycloak-tools.k8s.domain.com/auth/realms/MyRealm
    skip-openid-provider-tls-verify: true
    client-id: <redacted>
    client-secret: <redacted>
    listen: :3000
    enable-refresh-tokens: true
    redirection-url: https://pgadmin4-hal-dev.k8s.domain.com
    secure-cookie: false
    encryption-key: <redacted>
    upstream-url: http://127.0.0.1:80
    resources:
    - uri: /*
      roles:
      - group:admin
    enable-default-deny: true
    verbose: true
    enable-logging: true
    cors-origins:
    - '*'
    cors-methods:
    - GET
    - POST
    groups:
    - group1

```

Now when the ingress is up and running and I open up https://pgadmin4-hal-dev.k8s.domain.com, it redirects me to keycloak which is fine. I login with some credentials but then keycloak redirects me to https://127.0.0.1/login which is localhost. Shouldn't it be redirecting to https://pgadmin4-hal-dev.k8s.domain.com/login? I know this issue is not directly related to the helm chart but since you've mentioned a way of doing this, I tried but failed to make it work fully. Do I need to specify something more in the gatekeeper config? It would be great if I could get some help on this as I've been stuck for quite a while on this problem. Thanks
