### ISSUE TITLE
[charts/pgadmin4] Request to add image registry to values.yaml

### ISSUE THREAD

**Issue by qtomato3** [rowanruseler/helm-charts#57]
**Is your feature request related to a problem? Please describe.**
Current `values.yaml`  doesn't allow other image registry to be specified. This leads to default `docker.io` is used and this affects our pipelines due to public pull rate limit recently imposed by Docker.
* The same problem applies to `helm-charts/charts/pgadmin4/templates/tests/test-connection.yaml` where image `busybox` can only be pulled from `docker.io`.

**Describe the solution you'd like**
1. Add `registry` to image declaration under `helm-charts/charts/pgadmin4/values.yaml`, default value could be `docker.io`.
```
image:
  registry: docker.io     /// << --- added
  repository: dpage/pgadmin4
  tag: "4.28"
  pullPolicy: IfNotPresent
```
2. Use `registry` in all related templates, e.g. helm-charts/charts/pgadmin4/templates/deployment.yaml
```
image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you
