### ISSUE TITLE
[pgadmin4] apiVersion as a parameter at ingress configuration

### ISSUE THREAD

**Issue by mfbrj** [rowanruseler/helm-charts#65]
**Describe the bug**
In a Rancher cluster with kubernetes 1.19.6, Rancher logs displays this warning:
```
extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Version of Helm and Kubernetes**:
Kubernetes 1.19.6

**Which chart**: pgAdmin4

**What happened**:

**What you expected to happen**:
No warning at all.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Solution:
apiVersion as a parameter at ingress configuration. The values.yml should accept:
```
image:
  tag: "4.29"
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1

...
```
