### ISSUE TITLE
dpage/pgadmin4 image versions are out of sync in values.yaml

### ISSUE THREAD

**Issue by Plutoz01** [rowanruseler/helm-charts#97]
**Describe the bug**
For now there are two different version for docker image `dpage/pgadmin4` in `values.yaml` file.
First location:
```
image:
  registry: docker.io
  repository: dpage/pgadmin4
  tag: "5.1"
  pullPolicy: IfNotPresent
``` 
The second, out-of-sync (and disabled by default) section:
```
extraInitContainers: |
#   - name: add-folder-for-pgpass
#     image: "dpage/pgadmin4:4.23"
#     command: ["/bin/mkdir", "-p", "/var/lib/pgadmin/storage/pgadmin"]
#     volumeMounts:
#       - name: pgadmin-data
#         mountPath: /var/lib/pgadmin
#     securityContext:
#       runAsUser: 5050
```

**Which chart**:
`charts/pgadmin4`

I'm not sure if this difference is intended or not. I guess, it would be nice to use the same version to avoid downloading two different images resulting slower initial pod start after install.

Thanks,
Laszlo
